---
- name: Ensure cron is available
  ansible.builtin.apt:
    name: cron
    state: present
    update_cache: true

- name: Install docker
  ansible.builtin.include: docker.yml
  # this is only executed if explicity requested
  tags: ['never', 'docker']

- name: load site configuration
  ansible.builtin.include_vars:
    file: "{{ item }}"
    name: "{{ 'site_incl_vars_' ~ item | basename | splitext | first }}"
  with_fileglob:
    - "{{ site_config_dir }}/*.yaml"

- name: Set site configuration variable
  ansible.builtin.set_fact:
    sites: "{{ sites | default([]) + [lookup('vars', item)] }}"
  loop: "{{ query('varnames', '^site_incl_vars_(.*)$') }}"

- name: VO configuration
  block:
    - name: Create /etc/egi directory
      ansible.builtin.file:
        path: /etc/egi
        state: directory
        mode: 0755
    - name: Create /etc/egi/vos directory
      ansible.builtin.file:
        path: /etc/egi/vos
        state: directory
        mode: 0755
    # Loop over the VO configuration
    - name: create VO specific files
      ansible.builtin.include_tasks: vo-config.yml
      loop: "{{ vos | dict2items }}"
      no_log: true


- name: Configure cloud-info
  block:
    - name: Create /etc/egi directory
      ansible.builtin.file:
        path: /etc/egi
        state: directory
        mode: 0755
    - name: Create /etc/egi/cloud-info directory
      ansible.builtin.file:
        path: /etc/egi/cloud-info
        state: directory
        mode: 0755
    - name: Create /var/lock/cloud-info directory
      ansible.builtin.file:
        path: /var/lock/cloud-info
        state: directory
        mode: 0755
    - name: Create /var/log/cloud-info directory
      ansible.builtin.file:
        path: /var/log/cloud-info
        state: directory
        mode: 0755
    - name: site specific config
      ansible.builtin.include_tasks: cloud-info.yml
      vars:
        site: "{{ item }}"
        filename: "{{ item.gocdb | replace('.', '-') }}-{{ item.endpoint | hash('md5') }}"
      with_items:
        - "{{ sites }}"
      when: sites is iterable
