#- name: Install docker
#  include: docker.yml

- name: load site configuration
  include_vars:
    file: "{{ item }}"
    name: "{{ 'site_incl_vars_' ~ item|basename|splitext|first }}"
  with_fileglob:
  - vars/sites/*.yaml 

- set_fact:
    sites: "{{ sites|default([]) + [lookup('vars', item)] }}"
  loop: "{{ query('varnames', '^site_incl_vars_(.*)$') }}"

#- name: Handle secrets
#  include: vo-config.yml

- name: Configure cloud-info 
  include: cloud-info.yml
