---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-fedcloud-ops"
      include_role:
        name: "ansible-role-fedcloud-ops"
      vars:
        sites:
        - endpoint: https://example.com:5000/v3/
          gocdb: foo
          vos:
          - auth:
              project_id: a123456
            name: sample_vo
          - auth:
              project_id: b987659
            name: vo.example.com
