---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: pycontribs/ubuntu:latest
    pre_build_image: true
lint: ansible-lint
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
