---
name: Test role 

on: [pull_request]

jobs:
  molecule:
    name: Runs molecule for the ansible role 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Test 
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --debug
          molecule_command: converge

      - name: Test 2
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --debug
          molecule_command: converge
